# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 01:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_app', '0002_coursemanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseManager',
        ),
    ]
